import type { Abi } from "viem";
import local from "./gen/deployments.local.json";
import sepolia from "./gen/deployments.sepolia.json";
import disperseAbiJson from "./gen/LocalDisperse.abi.json";
import distributorAbiJson from "./gen/SignetDistributor.abi.json";
import tokenAbiJson from "./gen/SignetToken.abi.json";

/**
 * Per-chain contract registry.
 *  - 31337: generated by `npm run deploy:local` in @signet/contracts.
 *    `Disperse` is the LocalDisperse test double (grant-faithful copy of the
 *    TokenOps singleton's direct mode).
 *  - 11155111: `Disperse` is the REAL TokenOps DisperseConfidential singleton;
 *    token + distributor addresses are written by `npm run deploy:sepolia`
 *    (executed manually by the project owner, never by tooling).
 */
export type Deployment = {
  chainId: number;
  network: string;
  SignetToken: `0x${string}`;
  SignetDistributor: `0x${string}`;
  Disperse: `0x${string}`;
  /** Block to scan events from — real RPCs reject unbounded getLogs ranges. */
  deployBlock?: number;
};

export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";
export const SEPOLIA_CHAIN_ID = 11155111;
export const LOCAL_CHAIN_ID = 31337;

const DEPLOYMENTS: Record<number, Deployment> = {
  [LOCAL_CHAIN_ID]: local as Deployment,
  [SEPOLIA_CHAIN_ID]: sepolia as Deployment,
};

export function deploymentFor(chainId: number | undefined): Deployment | null {
  if (!chainId) return null;
  return DEPLOYMENTS[chainId] ?? null;
}

export function contractsDeployed(chainId: number | undefined): boolean {
  const d = deploymentFor(chainId);
  return !!d && d.SignetDistributor !== ZERO_ADDRESS;
}

export const distributorAbi = distributorAbiJson as Abi;
export const tokenAbi = tokenAbiJson as Abi;
/**
 * DirectDistribution/disclose surface. LocalDisperse mirrors the singleton's
 * direct-mode ABI exactly for the pieces Signet touches (the event + the two
 * disclose functions), so one ABI serves both chains for those call sites.
 */
export const disperseAbi = disperseAbiJson as Abi;

/** SignetToken has 6 decimals (OZ ERC-7984 default). UI "dollars" are whole tokens. */
export const TOKEN_DECIMALS = 6;
export const UNITS_PER_TOKEN = 10n ** BigInt(TOKEN_DECIMALS);

export function toUnits(wholeTokens: number): bigint {
  return BigInt(Math.round(wholeTokens)) * UNITS_PER_TOKEN;
}

export function fromUnits(units: bigint): number {
  return Number(units / UNITS_PER_TOKEN) + Number(units % UNITS_PER_TOKEN) / Number(UNITS_PER_TOKEN);
}
